### ISSUE TITLE
Won't install with python3

### ISSUE THREAD

**Issue by uSpike** [saltstack/pytest-logging#3]
There's an issue in `setup.py` reading `version.py` on python3:

``` shell
$ pip install -r requirements.txt 
Collecting pytest>=3 (from -r requirements.txt (line 1))
  Using cached pytest-3.0.3-py2.py3-none-any.whl
Collecting pytest-logging (from -r requirements.txt (line 2))
  Using cached pytest-logging-2015.11.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jro5pxxe/pytest-logging/setup.py", line 34, in <module>
        exec(rfh.read(), None, _LOCALS)  # pylint: disable=exec-used
      File "/home/pi/rpi/tests/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 105: ordinal not in range(128)
```

Probably due to the copyright symbols in `version.py`.

**Comment by s0undt3ch** [comment]
The work I did on this library is getting ported to pytest-catchlog which will eventually be renamed to pytest-logging, you should probably look into that instead. Still, thank you for reporting this.

**Comment by wouterdb** [comment]
is there any indication when pytest-catchlog will release this functionality? 
Or do you know of a working alternative?
